version: 0.1

environment_variables:
  plaintext:
    PIPELINE_NAME: "asf-base"
    IMAGE_HOST: "626226570674.dkr.ecr.us-east-1.amazonaws.com"
    IMAGE_1: "asf-base"
    IMAGE_2: "asf-gamma"
    CONFIGS_BUCKET: "hyp3-docker/configs"
    SOFTWARE_BUCKET: "hyp3-docker/software"
    MATURITY: "test"

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - aws codepipeline get-pipeline-state --name $PIPELINE_NAME --query 'stageStates[*].actionStates[?actionName==`Source`].currentRevision.revisionId' --output text | cut -c1-7 > sha1.txt

      - aws s3 cp s3://$SOFTWARE_BUCKET/ASF_MapReady.tar.gz ./docker/$IMAGE_1/etc/

      - aws s3 cp s3://$SOFTWARE_BUCKET/gamma_software_20161207.tar.gz ./docker/$IMAGE_2/etc/
  build:
    commands:
      - docker build -t $IMAGE_1:$MATURITY -f ./docker/$IMAGE_1/dockerfile ./docker/$IMAGE_1/
      - docker build -t $IMAGE_2:$MATURITY -f ./docker/$IMAGE_2/dockerfile.$MATURITY ./docker/$IMAGE_2/
  post_build:
    commands:
      - docker tag $IMAGE_1:$MATURITY $IMAGE_HOST/$IMAGE_1:latest
      - docker push $IMAGE_HOST/$IMAGE_1:latest
      - docker tag $IMAGE_1:$MATURITY $IMAGE_HOST/$IMAGE_1:$MATURITY
      - docker push $IMAGE_HOST/$IMAGE_1:$MATURITY
      - docker tag $IMAGE_1:$MATURITY $IMAGE_HOST/$IMAGE_1:$(cat sha1.txt)
      - docker push $IMAGE_HOST/$IMAGE_1:$(cat sha1.txt)

      - docker tag $IMAGE_2:$MATURITY $IMAGE_HOST/$IMAGE_2:latest
      - docker push $IMAGE_HOST/$IMAGE_2:latest
      - docker tag $IMAGE_2:$MATURITY $IMAGE_HOST/$IMAGE_2:$MATURITY
      - docker push $IMAGE_HOST/$IMAGE_2:$MATURITY
      - docker tag $IMAGE_2:$MATURITY $IMAGE_HOST/$IMAGE_2:$(cat sha1.txt)
      - docker push $IMAGE_HOST/$IMAGE_2:$(cat sha1.txt)
