FROM asf-base:latest

# The following are expected in the context
# ./etc/${GAMMA_VERSION}.tar.gz

ENV GAMMA_VERSION=gamma_software_20161207

LABEL gamma_version=${GAMMA_VERSION}

# INSTALL GAMMA here
COPY ./etc/${GAMMA_VERSION}.tar.gz /tmp/
RUN cd /tmp && tar xzvf "${GAMMA_VERSION}.tar.gz" && mv /tmp/${GAMMA_VERSION} /usr/local/gamma && rm -r /tmp/${GAMMA_VERSION}*

ENV GAMMA_HOME=/usr/local/${GAMMA_VERSION}
ENV MSP_HOME=${GAMMA_HOME}/MSP \
    ISP_HOME=${GAMMA_HOME}/ISP \
    DIFF_HOME=${GAMMA_HOME}/DIFF \
    DISP_HOME=${GAMMA_HOME}/DISP \
    LAT_HOME=${GAMMA_HOME}/LAT \
    IPTA_HOME=${GAMMA_HOME}/IPTA \
    GEO_HOME=${GAMMA_HOME}/GEO \
    GDFONTPATH=/usr/share/fonts/truetype/msttcorefonts \
    GAMMA_RASTER=BMP

ENV PATH=${PATH}:${DISP_HOME}/bin:${MSP_HOME}/bin:${ISP_HOME}/bin:${DIFF_HOME}/bin:${LAT_HOME}/bin:${IPTA_HOME}/bin:${GEO_HOME}/bin
ENV PATH=${PATH}:${MSP_HOME}/scripts:${ISP_HOME}/scripts/:${DIFF_HOME}/scripts:${LAT_HOME}/scripts:${IPTA_HOME}/scripts
