FROM asf-hyp3-base:test

ENV GAMMA_VERSION=gamma_software_20161207

LABEL maintainer="Alaska Satellite Facility" \
    gamma_version=${GAMMA_VERSION}

# GAMMA
RUN aws s3 cp s3://hyp3-docker/software/${GAMMA_VERSION}.tar.gz /tmp/
RUN cd /tmp && tar xzvf "${GAMMA_VERSION}.tar.gz" && mv /tmp/${GAMMA_VERSION} /usr/local/gamma && rm -r /tmp

WORKDIR /usr/local/cloud-proj/processing/proc
