# AWS Codebuild
# Based on GRFN
# INCOMPLETE
# http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html

version: 0.1


environment_variables:
  plaintext:
    PIPELINE_NAME: "hyp3-test"
    IMAGE_NAME: "docker-hyp3-base"
    IMAGE_HOST: ""  # "406893895021.dkr.ecr.us-east-1.amazonaws.com"


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - aws codepipeline get-pipeline-state --name $PIPELINE_NAME --query 'stageStates[*].actionStates[?actionName==`Source`].currentRevision.revisionId' --output text | cut -c1-7 > sha1.txt
      ??  # - aws s3 cp s3://grfn-software/ice.tar.bz2 .
      ??  # - tar -xjf ice.tar.bz2
      ??  # - mv isce-20160906 isce
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $IMAGE_HOST/$IMAGE_NAME:latest
      - docker tag $IMAGE_NAME:latest $IMAGE_HOST/$IMAGE_NAME:$(cat sha1.txt)
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_HOST/$IMAGE_NAME:latest
      - docker push $IMAGE_HOST/$IMAGE_NAME:$(cat sha1.txt)
